
-- Oracle Database In-Memory

-- COMPRESSION:
-- NO MEMCOPRESS
-- MEMCOMPRESS FOR DML
-- MEMCOMPRESS FOR QUERY LOW 
-- MEMCOMPRESS FOR QUERY HIGH 
-- MEMCOMPRESS FOR CAPACITY HIGH 
-- MEMCOMPRESS FOR CAPACITY LOW 

--PRIORITY
-- NONE, LOW, HIGH, CRITICAL, MEDIUM

DROP TABLE ALG1;

CREATE TABLE ALG1 (d integer, FIBBONACCI integer, FACTORIAL integer); 


insert into ALG1
SELECT                                                    
      d  , f AS FIBBONACCI, S AS FACTORIAL FROM   (SELECT   0 d  FROM DUAL)
MODEL
   DIMENSION BY (0 d)
   MEASURES (0 f, 0 s)
   RULES
      ITERATE (1000000) UNTIL (ITERATION_NUMBER = 80)
       (f [ITERATION_NUMBER] =
                            CASE ITERATION_NUMBER
                                WHEN 0 THEN 0
                                WHEN 1 THEN 1
                              ELSE
                                f[ITERATION_NUMBER - 2] + f[ITERATION_NUMBER - 1]
                            END,
      s [ITERATION_NUMBER] =
                  CASE ITERATION_NUMBER
                    WHEN 0 THEN 1
                    ELSE           
                    ITERATION_NUMBER * s[ITERATION_NUMBER - 1]
                  END);

--FULL SINTAXIS
/*
ALTER TABLE ALG1 
	INMEMORY
	 	PRIORITY CRITICAL
	 	DUPLICATE
	 	INMEMORY MEMCOMPRESS FOR CAPACITY HIGH (FACTORIAL)
	 	INMEMORY MEMCOMPRESS NO (D)
	 	NO INMEMORY (FIBBONACCI);

*/

-- IN MEMORY SOLVE 1
ALTER TABLE ALG1
 	INMEMORY
	 	INMEMORY (d, FIBBONACCI) 
	 	NO INMEMORY (FACTORIAL);

-- IN MEMORY SOLVE 2	 	
ALTER TABLE ALG1
	INMEMORY
	 	INMEMORY MEMCOMPRESS FOR CAPACITY HIGH(FACTORIAL)
	 	INMEMORY NO MEMCOMPRESS (D,FIBBONACCI);
	 	

--ALTER MATERIALIZED VIEW ALG1 INMEMORY;
